[package]
name = "codingup_qualifs"
version = "0.1.0"
edition = "2021"

[profile.profiling]
inherits = "release"
debug = true

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
hashbrown = "0.15"
rand = "0.9.0"
image = "0.25.5"
line_drawing = "1.0.0"